---
title: "Malaria incidents"
author: "Khadra Mohamed"
date: '2022-04-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading library}
library(malariaAtlas)
library(tidyverse)
library(tibble)
library(scales)
theme_set(theme_light())
```

```{r getting the data}
SOM <- as.tibble(malariaAtlas::getPR(ISO = "SOM", species = "BOTH"))
```

```{r data overview}
SOM %>% arrange(year_start) %>%
  view()

SOM %>% arrange(year_start) %>%
  count(method, sort = TRUE)

SOM %>% arrange(year_start) %>%
  count(species, sort = TRUE)

SOM %>% arrange(year_start) %>%
  count(year_start, sort = TRUE)
```

```{r prevalance over time}
SOM %>% 
  group_by(year_start) %>%
  summarise(examined = sum(examined),
            positive = sum(positive),
            studies = n()) %>%
  mutate(pr = positive / examined) %>%
  ggplot(aes(year_start, pr)) +
  geom_line()
```

```{r prevalance in different regions}
SOM %>%
  arrange(pr) %>%
  ggplot(aes(longitude, latitude, color = pr)) +
  borders("world", regions = "Somalia") +
  geom_point() +
  scale_color_gradient2(low = "blue", high = "red", midpoint= 0.5, labels = percent_format()) +
  theme_void() +
  coord_map()
```

```{r prevalance over decades}
SOM %>%
  mutate(decade = 10 * (year_start %/% 10)) %>%
  arrange(pr) %>%
  ggplot(aes(longitude, latitude, color = pr)) +
  borders("world", regions = "Somalia") +
  geom_point() +
  scale_color_gradient2(low = "blue", high = "red", midpoint= 0.5, labels = percent_format()) +
  facet_wrap(~ decade) +
  theme_void() +
  coord_map() +
  labs(color = "Prevalence")
```
