---
title: "Rdownloads"
author: "Khadra Mohamed"
date: '2022-04-24'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading library}
library(tidyverse)
library(scales)
library(countrycode)
theme_set(theme_light())
```

```{r reading the data}
r_downloads <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-30/r_downloads_year.csv")
```

```{r cleaning the data}
data_processed <- r_downloads %>%
  select(-X) %>%
  mutate(country_name = countrycode(country, "iso2c", "country.name"), sort = TRUE)
  
data_processed$date <- as.Date(data_processed$date)
```

```{r data overview}
data_processed %>%
  count(week = floor_date(date, "week")) %>%
  filter(week > min(week)) %>%
  ggplot(aes(week, n)) +
  geom_line() +
  expand_limits(y = 0)
```

```{r average of downloads per week day}
library(lubridate)

data_processed %>% 
  count(date) %>%
  group_by(day = wday(date, label = TRUE)) %>%
  summarise(average = mean(n)) %>%
  ggplot(aes(day, average, group = 1)) + 
  geom_line() +
  expand_limits(y = 0)
```

```{r country overview}
data_processed %>%
    count(country,   country = countrycode(country, "iso2c", "country.name"), sort = TRUE) %>%
  mutate(percent = n / sum(n)) %>%
  filter(!is.na(country)) %>%
  head(20) %>%
  mutate(country = fct_reorder(country, percent)) %>%
  ggplot(aes(country, percent)) +
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = percent_format())  
```

```{r version overview 1}
data_processed %>% 
  count(version, sort = TRUE)
```

```{r version overview 2}
data_processed %>%
  mutate(version = fct_lump(version, 8)) %>%
  count(date, version) %>%
  ggplot(aes(date, n, color = version)) +
  geom_line() + 
  theme(axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1, size = 8)) +
  theme(axis.text.y = element_text(size = 8)) +
  facet_wrap(~ version)
```

```{r when do people install R?}
data_processed %>%
  mutate(country = countrycode(country, "iso2c", "country.name")) %>%
  filter(!is.na(country)) %>%
  mutate(time = hms(time)) %>%
  count(hour = hour(time),
        country = fct_lump(country, 10)) %>%
  ggplot(aes(hour, n)) +
  geom_line() +
  expand_limits(y = 0) +
  facet_wrap(~ country, scales = "free_y")
```

```{r number of times R is installed in different countries}
data_processed %>%
  count(country_name = fct_lump(country_name, 10),
        week = floor_date(date, "week")) %>%
  filter(week >min(week)) %>%
  ggplot(aes(week, n, color = country_name)) +
  geom_line()
```

