---
title: "US wind data"
author: "Khadra Mohamed"
date: '2022-04-24'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading packages}
library(tidyverse)
```


```{r loading the data}
us_wind <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-06/us_wind.csv")
```


```{r exploring the data}
us_wind %>% 
  count(p_name, sort = TRUE)

us_wind %>% 
  count(t_state, sort = TRUE)
```


```{r wind turbine location}
us_wind %>%
  ggplot(aes(xlong, ylat)) +
  borders("state") +
           geom_point() + 
  coord_map() +
  theme_void()
```


```{r filtering outliers}
us_wind %>%
  filter(!t_state %in% c("AK", "HI", "GU", "PR")) %>%
  ggplot(aes(xlong, ylat)) +
  borders("state") +
           geom_point() + 
  coord_map() +
  theme_void()
```


```{r}
processed_data <- us_wind %>%
  filter(!t_state %in% c("AK", "HI", "GU", "PR"))

processed_data %>%
  group_by(p_name, t_state) %>%
  summarise(turbines = n())
```


```{r cleaning the data: each location is represented by one project}
projects <- processed_data %>%
  group_by(p_name, t_state) %>%
  summarise(turbines = n(),
            lon = mean(xlong),
            lat = mean(ylat),
            lon_sd = sd(xlong),
            lat_sd = sd(ylat))

# Data shows that the wind turbines in CA were clustered together (based on the sd), while in IA, the turbines were spread across the state.
```
```{r location of the projects}
projects %>%
  ggplot(aes(lon, lat, size = turbines)) +
  borders("state") +
           geom_point() + 
  coord_map() +
  theme_void()
```

```{r year when the projects started}
processed_data %>%
  distinct(p_name, p_year) %>%
  count(p_name, sort = TRUE)

# lets explore the biggest project:

processed_data %>%
  filter(p_name == "San Gorgonio Farms Wind Farm") %>%
  arrange(p_year)
```

```{r so, multiple projects have several years starting point, so we will look for the very first time a project started}
projects <- processed_data %>%
  group_by(p_name, t_state) %>%
  summarise(year = min(p_year), 
            turbines = n(),
            lon = mean(xlong),
            lat = mean(ylat),
            lon_sd = sd(xlong),
            lat_sd = sd(ylat))
```


```{r exploring when the projects started}
projects %>% 
  ggplot(aes(year)) +
  geom_histogram()
```

```{r more cleaning needed!}
processed_by_year_data <- us_wind %>%
  filter(!t_state %in% c("AK", "HI", "GU", "PR")) %>%
  mutate(p_year = ifelse(p_year  < -8000, NA, p_year),
         t_cap = ifelse(t_cap < 0, NA, t_cap))


projects_by_year <- processed_by_year_data %>%
  group_by(p_name, t_state) %>%
  summarise(year = min(p_year), 
            turbines = n(),
            lon = mean(xlong),
            lat = mean(ylat),
            lon_sd = sd(xlong),
            lat_sd = sd(ylat))
```

```{r projects per year}
projects_by_year %>% 
  ggplot(aes(year)) +
  geom_histogram()

projects_by_year %>%
  ggplot(aes(lon, lat, size = turbines, color = year)) +
  borders("state") +
  geom_point() +
  coord_map() +
  theme_void()
```

```{r exploring the turbine capacity (KW)}
projects_by_year <- processed_by_year_data %>%
  group_by(p_name, t_state) %>%
  summarise(year = min(p_year), 
            turbines = n(),
            total_capacity = sum(t_cap),
            lon = mean(xlong),
            lat = mean(ylat),
            lon_sd = sd(xlong),
            lat_sd = sd(ylat))
```


```{r turbine capacity (KW) over time}
projects_by_year %>%
  ggplot(aes(year, total_capacity)) +
  geom_point()

projects_by_year %>%
  ggplot(aes(year, total_capacity)) +
  geom_line()

projects_by_year %>%
  group_by(year) %>%
  summarise(median_capacity = median(total_capacity, na.rm = TRUE),
            projects = n()) %>%
  arrange(year) %>%
  view() %>%
  ggplot(aes(year, median_capacity)) +
  geom_line()
```


```{r capacity per turbine}
projects_by_year %>%
  ggplot(aes(year, total_capacity/turbines)) +
  geom_point()

trubine_models <-  processed_data %>%
  mutate_if(is.numeric, ~ifelse(. == -9999, NA, .)) %>%
  group_by(t_model) %>%
  summarise(t_cap = median(t_cap),
            t_hh = median(t_hh),
            t_rd = median(t_rd),
            t_rsa = median(t_rsa),
            t_ttlh = median(t_ttlh),
            turbines = n(),
            projects = n_distinct(p_name)) %>%
  arrange(desc(projects))

# total height effects capacity: 
trubine_models %>%
  ggplot(aes(t_ttlh, t_cap)) +
  geom_point()

# rotor swept area effects capacity: 

trubine_models %>%
  ggplot(aes(t_rd, t_cap)) +
  geom_point()
```


```{r}
library(gganimate)

projects_by_year %>%
  ggplot(aes(lon, lat, size = turbines, color = year)) +
  borders("state") +
  geom_point() +
  transition_states(
    year,
    transition_length = 2,
    state_length = 1
  ) +
  coord_map() +
  theme_void()
```


```{r}
projects_by_year %>%
  ggplot(aes(lon, lat, size = turbines, color = year)) +
  borders("state") +
  geom_point() +
  transition_time(year) +
  coord_map() +
  labs(title = "Year: {frame_time}") +
  theme_void()
```

